server {
    listen 3000;
    server_name _;

    # Stäng av Nginx inbyggda gissningar för omdirigeringar
    absolute_redirect off;
    port_in_redirect off;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm 200.html;
        
        # Försök ladda filen direkt, annars som html, annars index, annars fallback
        try_files $uri $uri.html $uri/index.html /200.html;
    }

    # Felhantering
    error_page 404 /200.html;
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }

    # Loggar till Cloud Run
    access_log /dev/stdout;
    error_log /dev/stderr;
}