server {
    listen 3000;
    server_name localhost;

    absolute_redirect off;
    port_in_redirect off;

    location / {
        root /usr/share/nginx/html;
        # Added 200.html as a fallback index file
        index index.html index.htm 200.html;
        try_files $uri $uri/ /200.html /index.html;
    }

    # Error handling
    error_page 404 /200.html;
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }

    # Logging to stdout for Cloud Run
    access_log /dev/stdout;
    error_log /dev/stderr;
}
